export const PRODUCT_CATEGORIES = [
  "NullValue",
  "JarCake",
  "Pastry",
  "CupCake",
  "Annniversary",
  "Birthday",
  "Wedding",
  "Pineapple",
  "Butterscotch",
  "Chocolate",
  "Redvelvet",
  "Strawberry",
  "Blackforest",
  "PopularDelight",
  "Decoration",
];
